common: &common
  adapter: mysql2
  encoding: utf8
  pool: 5
  connect_timeout:

development:
  <<: *common
  database: wire
  host: localhost
  socket: /var/mysql/mysql.sock
  username: root
  password: root

test:
  <<: *common
  database: wire_test
  host: localhost
  socket: /var/mysql/mysql.sock
  username: root
  password: root

staging:
  <<: *common

production:
  <<: *common